name: CI/CD Pipeline for Next.js App with pnpm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Matches your VPS Node.js version
          cache: "pnpm" # Cache pnpm dependencies

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Replaces pnpm ci for consistency

      # Step 5: Build the Next.js app
      - name: Build Next.js app
        run: pnpm run build
        env:
          NODE_ENV: production

      # Step 6: Run tests (optional, uncomment if you have tests)
      # - name: Run tests
      #   run: pnpm test
      #   if: always() # Run even if build fails, adjust based on your needs

      # Step 7: Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/usr/local/bin # Ensure pnpm is in PATH
            cd /var/www/nextjs/jed-landing
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 restart ecosystem.config.js
